name = "Bulgarian"
version = "0.1.1"

[macos]
system_pkg_id = "no.divvun.MacDivvun.bg"

[windows]
system_product_code = "{98D19DE4-ACAC-4CD1-B7BA-FC07D16C7B28}_is1"
legacy_product_codes = [
    { value = "6882FFC7-EF8B-4537-9373-9CFF82360412", kind = "nsis" },
    { value = "48C4C3F8-C80B-45AE-B3DB-4E0C25A9AA48", kind = "nsis" }
]
