template = "https://github.com/giellalt/template-lang-und"
rev_id = 346
template_sha = "f98c2a37b9866895a157f22bea282f596e7a321a"

[replacements]
__GLOTTOLOG_ID__ = "bulg1262"
__REPO__ = "lang-bul"
__UND2C__ = "bg"
__UNDEFINED__ = "Bulgarian"
__UND__ = "bul"
