template = "https://github.com/giellalt/template-lang-und"
rev_id = 332
template_sha = "517a754a9d968919fdaa1ed6e00d20145fac402c"

[replacements]
__GLOTTOLOG_ID__ = "bulg1262"
__REPO__ = "lang-bul"
__UND2C__ = "bg"
__UNDEFINED__ = "Bulgarian"
__UND__ = "bul"
