template = "https://github.com/giellalt/template-lang-und"
rev_id = 299
template_sha = "c2c940ccf19bf74ce9b697c688363766fc219a10"

[replacements]
__GLOTTOLOG_ID__ = "bulg1262"
__REPO__ = "lang-bul"
__UND2C__ = "bg"
__UNDEFINED__ = "Bulgarian"
__UND__ = "bul"
